services:
  linuxsoundscanner:
    image: $image_name$:$version$
    restart: unless-stopped
    environment:
      RMQ_HOST: host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./logs:/root/logs