services:
  linuxsoundscanner:
    uts: host
    image: $image_name$:$version$
    restart: unless-stopped
    environment:
      HOME: /tmp/linuxsoundscanner-home
      PULSE_SERVER: unix:/tmp/pulse/native
      RMQ_HOST: host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./logs:/tmp/linuxsoundscanner-home/logs
      - ${XDG_RUNTIME_DIR}/pulse:/tmp/pulse
      - ${HOME}/.config/pulse:/tmp/linuxsoundscanner-home/.config/pulse:ro