name: Build and Upload DEB Package

on:
  push:
    branches:
      - main
    tags:
      - 'Release-*'
  
  workflow_dispatch:

permissions:
  contents: write

env:
  BUILD_PRESET: linux-release
  BUILD_DIR: out/build/linux-release

jobs:
  build:
    if: github.ref != 'refs/pull/develop'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}  # Output the VERSION variable

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
         submodules: true
         fetch-depth: 0  # Fetch all history and tags

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build pkg-config libpulse-dev libglib2.0-dev

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg "${{ runner.temp }}/vcpkg"
        "${{ runner.temp }}/vcpkg/bootstrap-vcpkg.sh"
        echo "VCPKG_ROOT=${{ runner.temp }}/vcpkg" >> "$GITHUB_ENV"

    - name: Get version from Git tags
      id: get_version
      run: |
        # Get the latest Release tag
        LATEST_TAG=$(git describe --tags --match "Release-*" --abbrev=0)
        if [ -z "$LATEST_TAG" ]; then
          echo "No Release tag found. Using default version."
          echo "VERSION=1.0.0" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "LATEST_TAG: $LATEST_TAG"
        # Extract version number from the tag (e.g., Release-1.0.1 -> 1.0.1)
        VERSION_NUMBER=$(echo "$LATEST_TAG" | sed 's/^Release-//')
        echo "VERSION_NUMBER: $VERSION_NUMBER"
        # Get the distance since the latest tag
        DISTANCE=$(git rev-list --count "$LATEST_TAG"..HEAD)
        echo "DISTANCE: $DISTANCE"
        # Append -RC<distance> and increment third version number if distance is greater than 0
        if [ "$DISTANCE" -gt 0 ]; then
          # Increment the third number
          VERSION_NUMBER=$(echo "$VERSION_NUMBER" | awk -F. -v OFS=. '{$3++; print}')
          # Add RC info
          DISTANCE=$(printf "%03d" "$DISTANCE")
          VERSION="$VERSION_NUMBER-RC$DISTANCE"
        else
          VERSION="$VERSION_NUMBER"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Using version: $VERSION"

    - name: Configure CMake
      run: cmake --preset "${BUILD_PRESET}" -DPKG_VERSION=${{ steps.get_version.outputs.VERSION }}

    - name: Build and package
      run: cmake --build --preset "${BUILD_PRESET}"

    - name: Verify DEB package
      run: |
        for deb_file in "${BUILD_DIR}"/*.deb; do
          if [ -f "$deb_file" ]; then
            echo "Inspecting package: $deb_file"
            dpkg -c "$deb_file"
          fi
        done
        
    - name: Upload DEB package to GitHub Packages
      uses: actions/upload-artifact@v4
      with:
        name: SoundLinuxAgent-deb
        path: ${{ env.BUILD_DIR }}/*.deb
        overwrite: true

  publish:
    if: github.ref != 'refs/pull/develop'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download DEB package
      uses: actions/download-artifact@v4
      with:
        name: SoundLinuxAgent-deb
        path: build

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.build.outputs.version }}
        name: SoundLinuxAgent ${{ needs.build.outputs.version }}
        body: Release of SoundLinuxAgent ${{ needs.build.outputs.version }}
        files: build/*.deb
